[main]
# DJOS arranca en "Rendimiento" (se puede cambiar desde el ícono de energía de Plasma)
default=performance
battery_detection=true
sysfs_acpi_monitor=true

[profiles]
power-saver=powersave
balanced=djos-balanced
performance=djos

[battery]
balanced=balanced-battery
