# DJOS: conversión de frecuencia de máxima calidad y sin "surround falso" (evita que el audio del escritorio
# termine en la salida de auriculares/cue de la consola DJ)
stream.properties = {
    resample.quality = 10
    channelmix.upmix = false
}
